name: Ritual Marketing
favicon: null
layout_spectrum: 0.20982603426091373
typography_spectrum: 0.15607413509860635
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8688741920050234
  lightness: 0.8313187428284436
  saturation: 0.8445687138009816
  rhythmicContrast: 0.8531995166558772
purpose: []
